---
version: "2"
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    volumes:
      - /opt/appdata/letsencrypt/config:/config
    ports:
      - 80:80
      - 443:443
    networks:
      - internet
    environment:
      - PUID=1313
      - PGID=1313
      - EMAIL=email@gmail.com
      - URL=domain.com
      - SUBDOMAINS=blog
      - ONLY_SUBDOMAINS=true
      - DHLEVEL=4096
      - TZ=Europe/London
      - VALIDATION=http
    depends_on:
      - blog
    mem_limit: 256m
    cap_add: 
      - NET_ADMIN
    restart: always
  blog:
    image: ghost:3-alpine
    container_name: blog
    volumes:
      - /opt/appdata/blog:/var/lib/ghost/content
    networks:
      - internet
    environment:
      - NODE_ENV=production
      - url=https://blog.domain.com
    restart: unless-stopped
